CREATE TABLE timezones (   
	city varchar(80),   
	hour integer not null, 
	minute integer not null,
	primary key(city)
);


INSERT INTO timezones VALUES ('International Date Line West', -12, 0);
INSERT INTO timezones VALUES ('Midway Island, Samoa', -11, 0);
INSERT INTO timezones VALUES ('Hawaii', -10, 0);
INSERT INTO timezones VALUES ('Alaska', -9, 0);
INSERT INTO timezones VALUES ('Pacific Time (US & Canada)', -8, 0);
INSERT INTO timezones VALUES ('Tijuana, Baja California', -8, 0);
INSERT INTO timezones VALUES ('Arizona', -7, 0);
INSERT INTO timezones VALUES ('Chihuahua, La Paz, Mazatlan', -7, 0);
INSERT INTO timezones VALUES ('Mountain Time (US & Canada)', -7, 0);
INSERT INTO timezones VALUES ('Central America', -6, 0);
INSERT INTO timezones VALUES ('Central Time (US & Canada)', -6, 0);
INSERT INTO timezones VALUES ('Guadalajara, Mexico City, Monterrey', -6, 0);
INSERT INTO timezones VALUES ('Saskatchewan', -6, 0);
INSERT INTO timezones VALUES ('Bogota, Lima, Quito, Rio Branco', -5, 0);
INSERT INTO timezones VALUES ('Eastern Time (US & Canada)', -5, 0);
INSERT INTO timezones VALUES ('Indiana (East)', -5, 0);
INSERT INTO timezones VALUES ('Atlantic Time (Canada)', -4, 0);
INSERT INTO timezones VALUES ('Caracas, La Paz', -4, 0);
INSERT INTO timezones VALUES ('Manaus', -4, 0);
INSERT INTO timezones VALUES ('Santiago', -4, 0);
INSERT INTO timezones VALUES ('Newfoundland', -3, 30);
INSERT INTO timezones VALUES ('Brasilia', -3, 0);
INSERT INTO timezones VALUES ('Buenos Aires, Georgetown', -3, 0);
INSERT INTO timezones VALUES ('Greenland', -3, 0);
INSERT INTO timezones VALUES ('Montevideo', -3, 0);
INSERT INTO timezones VALUES ('Mid-Atlantic', -2, 0);
INSERT INTO timezones VALUES ('Cape Verde Is.', -1, 0);
INSERT INTO timezones VALUES ('Azores', -1, 0);
INSERT INTO timezones VALUES ('Casablanca, Monrovia, Reykjavik', 0, 0);
INSERT INTO timezones VALUES ('GMT: Dublin, Edinburgh, Lisbon, London', 0, 0);
INSERT INTO timezones VALUES ('Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna', 1, 0);
INSERT INTO timezones VALUES ('Belgrade, Bratislava, Budapest, Ljubljana, Prague', 1, 0);
INSERT INTO timezones VALUES ('Brussels, Copenhagen, Madrid, Paris', 1, 0);
INSERT INTO timezones VALUES ('Sarajevo, Skopje, Warsaw, Zagreb', 1, 0);
INSERT INTO timezones VALUES ('West Central Africa', 1, 0);
INSERT INTO timezones VALUES ('Amman', 2, 0);
INSERT INTO timezones VALUES ('Athens, Bucharest, Istanbul', 2, 0);
INSERT INTO timezones VALUES ('Beirut', 2, 0);
INSERT INTO timezones VALUES ('Cairo', 2, 0);
INSERT INTO timezones VALUES ('Harare, Pretoria', 2, 0);
INSERT INTO timezones VALUES ('Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius', 2, 0);
INSERT INTO timezones VALUES ('Jerusalem', 2, 0);
INSERT INTO timezones VALUES ('Minsk', 2, 0);
INSERT INTO timezones VALUES ('Windhoek', 2, 0);
INSERT INTO timezones VALUES ('Kuwait, Riyadh, Baghdad', 3, 0);
INSERT INTO timezones VALUES ('Moscow, St. Petersburg, Volgograd', 3, 0);
INSERT INTO timezones VALUES ('Nairobi', 3, 0);
INSERT INTO timezones VALUES ('Tbilisi', 3, 0);
INSERT INTO timezones VALUES ('Tehran', 3, 30);
INSERT INTO timezones VALUES ('Abu Dhabi, Muscat', 4, 0);
INSERT INTO timezones VALUES ('Baku', 4, 0);
INSERT INTO timezones VALUES ('Yerevan', 4, 0);
INSERT INTO timezones VALUES ('Kabul', 4, 30);
INSERT INTO timezones VALUES ('Yekaterinburg', 5, 0);
INSERT INTO timezones VALUES ('Islamabad, Karachi, Tashkent', 5, 0);
INSERT INTO timezones VALUES ('Sri Jayawardenapura', 5, 30);
INSERT INTO timezones VALUES ('Chennai, Kolkata, Mumbai, New Delhi', 5, 30);
INSERT INTO timezones VALUES ('Kathmandu', 5, 45);
INSERT INTO timezones VALUES ('Almaty, Novosibirsk', 6, 0);
INSERT INTO timezones VALUES ('Astana, Dhaka', 6, 0);
INSERT INTO timezones VALUES ('Yangon (Rangoon)', 6, 30);
INSERT INTO timezones VALUES ('Bangkok, Hanoi, Jakarta', 7, 0);
INSERT INTO timezones VALUES ('Krasnoyarsk', 7, 0);
INSERT INTO timezones VALUES ('Beijing, Chongqing, Hong Kong, Urumqi', 8, 0);
INSERT INTO timezones VALUES ('Kuala Lumpur, Singapore', 8, 0);
INSERT INTO timezones VALUES ('Irkutsk, Ulaan Bataar', 8, 0);
INSERT INTO timezones VALUES ('Perth', 8, 0);
INSERT INTO timezones VALUES ('Taipei', 8, 0);
INSERT INTO timezones VALUES ('Osaka, Sapporo, Tokyo', 9, 0);
INSERT INTO timezones VALUES ('Seoul', 9, 0);
INSERT INTO timezones VALUES ('Yakutsk', 9, 0);
INSERT INTO timezones VALUES ('Adelaide', 9, 30);
INSERT INTO timezones VALUES ('Darwin', 9, 30);
INSERT INTO timezones VALUES ('Brisbane', 10, 0);
INSERT INTO timezones VALUES ('Canberra, Melbourne, Sydney', 10, 0);
INSERT INTO timezones VALUES ('Hobart', 10, 0);
INSERT INTO timezones VALUES ('Guam, Port Moresby', 10, 0);
INSERT INTO timezones VALUES ('Vladivostok', 10, 0);
INSERT INTO timezones VALUES ('Magadan, Solomon Is., New Caledonia', 11, 0);
INSERT INTO timezones VALUES ('Auckland, Wellington', 12, 0);
INSERT INTO timezones VALUES ('Fiji, Kamchatka, Marshall Is.', 12, 0);
